name: llm-graph
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2024.8.30
  - cloudpickle=3.0.0
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.1.0
  - future=0.18.3
  - hyperopt=0.2.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py4j=0.10.9.7
  - pybind11-abi=4
  - pygments=2.18.0
  - python=3.10
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - scipy=1.13.1
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - accelerate==1.5.2
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.9.0
    - astor==0.8.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - brokenaxes==0.6.2
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - cicflowmeter==0.1.6
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - distro==1.9.0
    - dpkt==1.9.8
    - exceptiongroup==1.2.2
    - filelock==3.11.0
    - flowcontainer==7.4
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - gensim==4.3.3
    - git-filter-repo==2.47.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.29.3
    - idna==3.8
    - importlib-metadata==8.6.1
    - importlib-resources==6.4.4
    - jinja2==3.1.4
    - jiter==0.9.0
    - joblib==1.4.2
    - json-tricks==3.17.3
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - nni==3.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.570.86
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu12==12.1.105
    - openai==1.68.2
    - pandas==2.2.2
    - peft==0.15.0
    - pillow==10.4.0
    - prettytable==3.14.0
    - psutil==6.0.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pygcl==0.1.2
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pythonwebhdfs==0.2.3
    - pytz==2024.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - responses==0.25.6
    - safetensors==0.5.3
    - scapy==2.5.0
    - schema==0.7.7
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - sentence-transformers==3.4.1
    - simplejson==3.20.1
    - smart-open==7.0.4
    - sniffio==1.3.1
    - sympy==1.13.2
    - threadpoolctl==3.5.0
    - tokenizers==0.21.1
    - torch==2.4.0
    - torch-geometric==2.6.1
    - torchaudio==2.4.0
    - torchvision==0.19.0
    - transformers==4.50.0
    - triton==3.0.0
    - typeguard==4.1.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - websockets==14.2
    - wrapt==1.16.0
    - xlrd==2.0.1
    - yarl==1.9.4
    - zipp==3.20.1